### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by LaimaL** [Viva-con-Agua/barcheck#102]
1) Save page - without tick - will be created
2) Home page /Landing page / Login

**Comment by ansgarmax** [comment]
Please find mockups here:
https://www.dropbox.com/sh/u0ntfljfdg5zpql/AACFlup2LfYbV11PPymDL0Oaa?dl=0

Notes:
2. Landing Page
Plz "Design" text box in 0.0 in dependency of other text areas which are shown during User-Barcheck-Process.

2. Login
 I created an alternate version of 0.0.1; this is in dependency of the firebase connection since I dont know yet how the standard procedure runs / looks like (in terms of "Wrong Password is entered etc.") 
We should have a quick talk on that.
